#!/usr/bin/env python3

import argparse
import os

import google_cloud_run_deploy

parser = argparse.ArgumentParser(
    description="Deploy the bentoml bundle on Google Cloud Run",
    epilog="Check out https://github.com/bentoml/google-cloud-run-deploy#readme to know more",
)
parser.add_argument("bento_bundle_path", help="Path to bentoml bundle")
parser.add_argument(
    "deployment_name", help="The name you want to use for your deployment"
)
parser.add_argument(
    "config_json",
    help="The config file for your deployment",
    default=os.path.join(os.getcwd(), "cloud_run_config.json"),
    nargs="?",
)
args = parser.parse_args()

deployment_spec = google_cloud_run_deploy.get_configuration_value(args.config_json)
google_cloud_run_deploy.deploy(args.bento_bundle_path, args.deployment_name, deployment_spec)
google_cloud_run_deploy.utils.console.print("[bold green]Deployment Successful!")
# show details of the deployment
google_cloud_run_deploy.describe(args.deployment_name, args.config_json)
